all:				UDPServer.class UDPClient.class UDPServer2.class UDPClient2.class

UDPClient2.class:		UDPClient2.java
				@javac UDPClient2.java

UDPServer2.class:		UDPServer2.java
				@javac UDPServer2.java

UDPClient.class:		UDPClient.java
				@javac UDPClient.java

UDPServer.class:		UDPServer.java
				@javac UDPServer.java

clean:
				@rm -rf *.class *~
