all:				Server.class Client.class Person.class

Client.class:			Client.java
				@javac Client.java

Server.class:			Server.java
				@javac Server.java

Person.class:			Person.java
				@javac Person.java

clean:
				@rm -rf *.class *~
