all:				TCPServer.class TCPClient.class TCPClient2.class

TCPClient2.class:		TCPClient2.java
				@javac TCPClient2.java

TCPClient.class:		TCPClient.java
				@javac TCPClient.java

TCPServer.class:		TCPServer.java
				@javac TCPServer.java

clean:
				@rm -rf *.class *~
